/*
Dofusdude

Testing SetsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dodugo

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_dodugo_SetsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test SetsApiService GetAllSetsList", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var language string
        var game string

        resp, httpRes, err := apiClient.SetsApi.GetAllSetsList(context.Background(), language, game).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test SetsApiService GetSetsList", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var language string
        var game string

        resp, httpRes, err := apiClient.SetsApi.GetSetsList(context.Background(), language, game).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test SetsApiService GetSetsSearch", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var language string
        var game string

        resp, httpRes, err := apiClient.SetsApi.GetSetsSearch(context.Background(), language, game).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test SetsApiService GetSetsSingle", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var language string
        var ankamaId int32
        var game string

        resp, httpRes, err := apiClient.SetsApi.GetSetsSingle(context.Background(), language, ankamaId, game).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
